// Fee integrity for Robinhood Chain — the same layer as feeIntegrity.ts,
// for the EVM treasury.
//
// The honest ceiling is stated in feeIntegrity.ts and applies here word for
// word: this defeats the casual crack (grep the packaged app for the
// treasury, edit it), not a debugger. The canonical EVM treasury is carried
// as an obfuscated byte blob plus a SHA-256 of the address; the trade path
// resolves the treasury THROUGH this module and always gets the canonical
// decoded value, so editing the readable `EVM_TREASURY_ADDRESS` in a cracked
// build redirects nothing. A corrupt blob fails CLOSED for billing (no fee)
// and never blocks a trade.
//
// Its own keystream seed, so the Solana decoder cannot be pointed at this
// blob and vice versa. Regenerate after changing the treasury with:
//   node scripts/gen-fee-integrity.mjs

import { sha256Hex } from './hash';

// Encoded canonical EVM treasury. Regenerated by the script above — do NOT
// hand-edit; the checksum below must match.
const BLOB: number[] = [
  96, 8, 2, 109, 180, 127, 66, 241, 112, 112, 94, 57, 86, 113, 150, 182, 34, 250, 117, 104, 27, 89, 124, 137, 196, 104, 246, 25, 115, 128, 17, 69, 86, 4, 195, 132, 41, 253, 88, 100, 241, 155,
];
const CANON_SHA256 = 'ffc378b6d0b8774e3a5331f6d13a371ec25be2c8c55bf4ce25ab298b294462c2';

const A = 1103515245;
const C = 12345;
const M = 2 ** 31;
const S0 = 0x484f4f44;

function decodeCanonical(): string {
  let s = S0;
  let out = '';
  for (let i = 0; i < BLOB.length; i++) {
    s = (A * s + C) % M;
    const k = (s >>> 7) & 0xff;
    out += String.fromCharCode(BLOB[i] ^ k);
  }
  return out;
}

export type EvmFeeIntegrityState = 'ok' | 'address-tampered' | 'blob-corrupt';

export interface EvmFeeIntegrityResult {
  /** The address the fee MUST go to. Always the canonical one; '' when the
   *  blob cannot be trusted (billing then fails closed). */
  treasury: string;
  state: EvmFeeIntegrityState;
  intact: boolean;
}

/**
 * Resolve the EVM treasury through the integrity layer. `readable` is
 * `EVM_TREASURY_ADDRESS` from evm.ts, passed in to avoid a circular import.
 * Callers use the returned `treasury`, never the raw constant.
 */
export function resolveEvmTreasury(readable: string): EvmFeeIntegrityResult {
  const canonical = decodeCanonical();
  if (!BLOB.length || sha256Hex(canonical) !== CANON_SHA256) {
    return { treasury: '', state: 'blob-corrupt', intact: false };
  }
  // Addresses compare case-insensitively: a checksum-cased and a lowercased
  // copy of the same treasury are the same destination, not a tamper. Anything
  // that is not a string is a tamper too — and must not throw, because this
  // runs on the trade path.
  const seen = typeof readable === 'string' ? readable.trim().toLowerCase() : '';
  if (seen !== canonical.toLowerCase()) {
    return { treasury: canonical, state: 'address-tampered', intact: false };
  }
  return { treasury: canonical, state: 'ok', intact: true };
}

/** Canonical EVM treasury, no comparison — '' when the blob is corrupt. */
export function canonicalEvmTreasury(): string {
  const canonical = decodeCanonical();
  return BLOB.length && sha256Hex(canonical) === CANON_SHA256 ? canonical : '';
}
