// Fee integrity — the tamper-resistant layer under the fee system.
//
// ─── The honest ceiling, stated once ──────────────────────────────────
//
// This runs on the user's machine, so a determined attacker with a debugger
// can defeat any of it. That is a property of client-side software, not a flaw
// here. What this DOES do is defeat the attack that would actually cost real
// money: the casual crack — someone opens the packaged app, greps for the
// treasury address or the fee constant, and edits it to point trades at their
// own wallet or to zero the fee.
//
// Against that attacker this layer is genuinely effective, and it costs a legit
// user nothing: it runs once per trade, never in a render loop, and an
// untampered build always passes it instantly.
//
// ─── How it works ─────────────────────────────────────────────────────
//
// The real treasury is NOT stored only as the readable `TREASURY_ADDRESS`
// string in fees.ts. It is also carried here as an obfuscated byte blob plus a
// SHA-256 of the address. The trade path resolves the treasury THROUGH this
// module, which:
//
//   1. decodes the canonical address from the blob,
//   2. checks it against its own checksum (blob not corrupted),
//   3. compares it to the readable `TREASURY_ADDRESS`,
//   4. returns the CANONICAL address regardless — so editing the readable
//      string in a cracked build does not redirect one lamport; the fee still
//      goes where the blob says.
//
// To actually redirect the fee, a cracker must find the blob, understand the
// keystream, re-encode a new address, AND fix the checksum — in an obfuscated,
// fuse-locked bundle. That is the cost increase this buys. A grep-and-replace,
// which is what nearly everyone would try, changes a decoy and does nothing.
//
// Regenerate the blob after changing the treasury with:
//   node scripts/gen-fee-integrity.mjs

import { sha256Hex } from './hash';

// Encoded canonical treasury (see header). Regenerated by the script above —
// do NOT hand-edit; the checksum below must match.
const BLOB: number[] = [
  100, 193, 13, 86, 213, 97, 67, 167, 35, 188, 117, 50, 219, 238, 225, 148, 103, 116, 1, 71, 228, 245, 6, 81, 158, 69, 139, 4, 50, 198, 45, 96, 18, 134, 69, 31, 19, 42, 78, 34, 34, 159, 69, 186,
];
const CANON_SHA256 = 'f64771be0c19a1eefeb6b2c4d4cd6e8ec4df20b90697e4bb64cd961595c7e03b';

// Keystream parameters. Deliberately not named "key" or "secret" — a grep for
// those turns up nothing.
const A = 1103515245;
const C = 12345;
const M = 2 ** 31;
const S0 = 0x4b525950;

function decodeCanonical(): string {
  let s = S0;
  let out = '';
  for (let i = 0; i < BLOB.length; i++) {
    s = (A * s + C) % M;
    const k = (s >>> 7) & 0xff;
    out += String.fromCharCode(BLOB[i] ^ k);
  }
  return out;
}

export type FeeIntegrityState = 'ok' | 'address-tampered' | 'blob-corrupt';

export interface FeeIntegrityResult {
  /** The address the fee MUST go to. Always the canonical one. */
  treasury: string;
  state: FeeIntegrityState;
  /** True only when everything agrees — the readable constant, the blob, and
   *  the checksum. */
  intact: boolean;
}

/**
 * Resolve the treasury address through the integrity layer.
 *
 * `readable` is `TREASURY_ADDRESS` from fees.ts, passed in rather than imported
 * to avoid a circular import. The returned `treasury` is ALWAYS the canonical
 * decoded address — callers must use it, not the raw constant, so that editing
 * the constant in a cracked build cannot redirect the fee.
 */
export function resolveTreasury(readable: string): FeeIntegrityResult {
  const canonical = decodeCanonical();

  // The blob itself is corrupt or was re-encoded without fixing the checksum.
  if (sha256Hex(canonical) !== CANON_SHA256) {
    // We cannot trust the decoded value. Fail CLOSED for billing: no verified
    // address means no fee is charged (better than sending to a wrong one),
    // but the app keeps working — this must never block a trade.
    return { treasury: '', state: 'blob-corrupt', intact: false };
  }

  if (readable.trim() !== canonical) {
    // The readable constant was edited. The canonical still wins.
    return { treasury: canonical, state: 'address-tampered', intact: false };
  }

  return { treasury: canonical, state: 'ok', intact: true };
}

/** Canonical address, no comparison — for places that just need the truth. */
export function canonicalTreasury(): string {
  const canonical = decodeCanonical();
  return sha256Hex(canonical) === CANON_SHA256 ? canonical : '';
}
