// Attribution integrity — the tamper-resistant layer under Discord presence.
//
// Same shape and the same honest ceiling as feeIntegrity.ts: this runs on the
// user's machine, so a debugger beats it. What it defeats is the casual crack
// — open the packaged app, grep for the Discord client id or the krypt.cc
// button, and edit it out so the build advertises nothing (or advertises
// somebody else).
//
// The identity is carried here as an obfuscated blob plus a SHA-256 of the
// packed record. The presence path resolves THROUGH this module, which:
//
//   1. decodes the canonical identity from the blob,
//   2. checks it against its own checksum (blob not corrupted),
//   3. compares it to the readable PRESENCE constants,
//   4. returns the CANONICAL identity regardless — so editing the readable
//      constants in a cracked build changes a decoy and publishes nothing
//      different.
//
// A different keystream from feeIntegrity.ts on purpose: finding one blob
// must not hand over the other.
//
// Regenerate after changing shared/presence.ts with:
//   node scripts/gen-presence-integrity.mjs

import { sha256Hex } from './hash';
import { PRESENCE, packIdentity, unpackIdentity, type PresenceIdentity } from './presence';

// Encoded canonical identity (see header). Regenerated by the script above —
// do NOT hand-edit; the checksum below must match.
const TABLE: number[] = [
  6, 230, 185, 176, 163, 207, 107, 89, 10, 183, 210, 236, 19, 190, 8, 154, 242, 235, 122, 247, 211, 160,
  45, 153, 186, 254, 72, 245, 140, 116, 84, 197, 137, 6, 36, 208, 182, 241, 210, 250, 195, 92, 73, 204,
  181, 233, 9, 211, 136, 88, 214, 1, 225, 188, 178, 137, 243, 199, 104, 140, 57, 207, 74, 66, 144, 187,
  233, 177, 230, 55, 67, 88, 228, 197, 106, 252, 228, 77, 66, 153, 186, 167, 118, 181, 99, 249, 176, 7,
  232, 111, 75, 216, 122, 14, 52, 138, 173, 174, 23, 73, 120, 216, 170, 69, 141, 124, 52, 237, 71, 54,
  8, 237, 13, 251, 59, 68, 177, 125, 45, 124, 54, 153, 165, 137, 214, 47, 102, 181, 101, 198, 15, 193,
  123, 232, 42, 234, 18, 186, 31, 9, 107, 4, 171, 156, 24,
];
const TABLE_SHA256 = '3d285e6c0ec415cd8003aef0b6569a26a1a66690a720aa89587d8dc4b0f5f5be';

// Keystream parameters. Named as if they were table geometry so a grep for
// "key" or "secret" turns up nothing.
const ROWS = 1664525;
const COLS = 1013904223;
const SPAN = 2 ** 32;
const ORIGIN = 0x6b727970;

function decodeCanonical(): string {
  let s = ORIGIN;
  let out = '';
  for (let i = 0; i < TABLE.length; i++) {
    s = (Math.imul(ROWS, s) + COLS) % SPAN;
    const k = (s >>> 11) & 0xff;
    out += String.fromCharCode(TABLE[i] ^ k);
  }
  return out;
}

export type PresenceIntegrityState = 'ok' | 'identity-tampered' | 'blob-corrupt';

export interface PresenceIntegrityResult {
  /** The identity presence MUST publish. Always the canonical one, or null
   *  when the blob itself cannot be trusted. */
  identity: PresenceIdentity | null;
  state: PresenceIntegrityState;
  /** True only when the readable constants, the blob and the checksum agree. */
  intact: boolean;
}

/**
 * Resolve the presence identity through the integrity layer.
 *
 * The returned identity is ALWAYS the canonical decoded one — callers must
 * use it rather than the readable PRESENCE constants, so that editing those
 * in a cracked build cannot change what Discord shows.
 */
export function resolvePresence(readable: PresenceIdentity = PRESENCE): PresenceIntegrityResult {
  const packed = decodeCanonical();

  // The blob is corrupt, or was re-encoded without fixing the checksum.
  if (sha256Hex(packed) !== TABLE_SHA256) {
    // Fail CLOSED for presence: no verified identity means publish nothing,
    // which is better than publishing someone else's. Never blocks the app.
    return { identity: null, state: 'blob-corrupt', intact: false };
  }

  const canonical = unpackIdentity(packed);
  if (!canonical) return { identity: null, state: 'blob-corrupt', intact: false };

  if (packIdentity(readable) !== packed) {
    // The readable constants were edited. The canonical still wins.
    return { identity: canonical, state: 'identity-tampered', intact: false };
  }

  return { identity: canonical, state: 'ok', intact: true };
}

/** Canonical identity, no comparison — for places that just need the truth. */
export function canonicalPresence(): PresenceIdentity | null {
  const packed = decodeCanonical();
  if (sha256Hex(packed) !== TABLE_SHA256) return null;
  return unpackIdentity(packed);
}
