// Attribution integrity — the tamper-resistant layer under Discord presence.
//
// Same shape and the same honest ceiling as feeIntegrity.ts: this runs on the
// user's machine, so a debugger beats it. What it defeats is the casual crack
// — open the packaged app, grep for the Discord client id or the krypt.cc
// button, and edit it out so the build advertises nothing (or advertises
// somebody else).
//
// The identity is carried here as an obfuscated blob plus a SHA-256 of the
// packed record. The presence path resolves THROUGH this module, which:
//
//   1. decodes the canonical identity from the blob,
//   2. checks it against its own checksum (blob not corrupted),
//   3. compares it to the readable PRESENCE constants,
//   4. returns the CANONICAL identity regardless — so editing the readable
//      constants in a cracked build changes a decoy and publishes nothing
//      different.
//
// A different keystream from feeIntegrity.ts on purpose: finding one blob
// must not hand over the other.
//
// Regenerate after changing shared/presence.ts with:
//   node scripts/gen-presence-integrity.mjs

import { sha256Hex } from './hash';
import { PRESENCE, packIdentity, unpackIdentity, type PresenceIdentity } from './presence';

// Encoded canonical identity (see header). Regenerated by the script above —
// do NOT hand-edit; the checksum below must match.
const TABLE: number[] = [
  6, 230, 185, 176, 163, 207, 107, 89, 10, 183, 210, 236, 19, 190, 8, 154, 242, 235, 122, 247, 211, 160,
  45, 153, 186, 254, 72, 245, 140, 116, 84, 197, 137, 6, 36, 208, 182, 241, 210, 250, 195, 92, 73, 204,
  181, 233, 9, 211, 136, 88, 214, 1, 225, 188, 221, 176, 216, 238, 76, 246, 21, 208, 94, 94, 144, 191,
  234, 248, 243, 55, 28, 73, 224, 198, 39, 245, 227, 71, 67, 157, 178, 225, 117, 239, 43, 206, 190, 32,
  188, 62, 75, 217, 113, 17, 28, 145, 158, 171, 47, 119, 59, 212, 139, 70, 172, 31, 66, 233, 125,
];
const TABLE_SHA256 = '0e63d8029152bd9859bff3bb1e96911cee9a87dba1c6e0a29d2d78526d5da9b7';

// Keystream parameters. Named as if they were table geometry so a grep for
// "key" or "secret" turns up nothing.
const ROWS = 1664525;
const COLS = 1013904223;
const SPAN = 2 ** 32;
const ORIGIN = 0x6b727970;

function decodeCanonical(): string {
  let s = ORIGIN;
  let out = '';
  for (let i = 0; i < TABLE.length; i++) {
    s = (Math.imul(ROWS, s) + COLS) % SPAN;
    const k = (s >>> 11) & 0xff;
    out += String.fromCharCode(TABLE[i] ^ k);
  }
  return out;
}

export type PresenceIntegrityState = 'ok' | 'identity-tampered' | 'blob-corrupt';

export interface PresenceIntegrityResult {
  /** The identity presence MUST publish. Always the canonical one, or null
   *  when the blob itself cannot be trusted. */
  identity: PresenceIdentity | null;
  state: PresenceIntegrityState;
  /** True only when the readable constants, the blob and the checksum agree. */
  intact: boolean;
}

/**
 * Resolve the presence identity through the integrity layer.
 *
 * The returned identity is ALWAYS the canonical decoded one — callers must
 * use it rather than the readable PRESENCE constants, so that editing those
 * in a cracked build cannot change what Discord shows.
 */
export function resolvePresence(readable: PresenceIdentity = PRESENCE): PresenceIntegrityResult {
  const packed = decodeCanonical();

  // The blob is corrupt, or was re-encoded without fixing the checksum.
  if (sha256Hex(packed) !== TABLE_SHA256) {
    // Fail CLOSED for presence: no verified identity means publish nothing,
    // which is better than publishing someone else's. Never blocks the app.
    return { identity: null, state: 'blob-corrupt', intact: false };
  }

  const canonical = unpackIdentity(packed);
  if (!canonical) return { identity: null, state: 'blob-corrupt', intact: false };

  if (packIdentity(readable) !== packed) {
    // The readable constants were edited. The canonical still wins.
    return { identity: canonical, state: 'identity-tampered', intact: false };
  }

  return { identity: canonical, state: 'ok', intact: true };
}

/** Canonical identity, no comparison — for places that just need the truth. */
export function canonicalPresence(): PresenceIdentity | null {
  const packed = decodeCanonical();
  if (sha256Hex(packed) !== TABLE_SHA256) return null;
  return unpackIdentity(packed);
}
